name: Login Demo

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:     
  specflowtests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1'
          
      - name: Install Google Chrome
        uses: montudor/chrome-webstore-download@v1
        with:
          extension-id: 'google-chrome'
          path: c:\temp\chrome

      - name: Add Chrome to PATH
        run: |
          echo "::add-path::C:\\temp\\chrome"

      - name: Install Chrome WebDriver
        run: |
          choco install chromedriver
          
      - uses: cryptic-wizard/run-specflow-tests@v1.3.3
        with:
          test-assembly-path: LoginDemo/bin/Debug/netcoreapp3.1
          test-assembly-dll: LoginDemo.dll
          test-execution-json: TestExecution.json
          output-html: MyTestResults.html
          logger: trx
          logger-file-name: MyTestResults.trx
      - name: Configure Git
        run: |
          git config --global user.name "laibashaikh28"
          git config --global user.email "laibaovais05@gmail.com"
      - name: Add changes
        run: git add -A
      - name: Commit changes
        run: git commit -m "commit message"
      - name: Push changes
        run: git push
