name: Login Demo

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:     
  specflowtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1'

      - name: Install Chrome and Chrome WebDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          sudo apt install -y chromium-chromedriver
          
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
    
      - uses: cryptic-wizard/run-specflow-tests@v1.3.3
        with:
          browser: chrome
          test-assembly-path: LoginDemo/bin/Debug/netcoreapp3.1
          test-assembly-dll: LoginDemo.dll
          test-execution-json: TestExecution.json
          output-html: MyTestResults.html
          logger: trx
          logger-file-name: MyTestResults.trx
      - name: Configure Git
        run: |
          git config --global user.name "laibashaikh28"
          git config --global user.email "laibaovais05@gmail.com"
      - name: Add changes
        run: git add -A
      - name: Commit changes
        run: git commit -m "commit message"
      - name: Push changes
        run: git push
